name: .NET CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./LeafLight-API.sln

    - name: Lint Check
      run: |
        dotnet format style ./LeafLight-API.sln --verify-no-changes
        dotnet format analyzers ./LeafLight-API.sln --verify-no-changes
      env:
        DOTNET_NOLOGO: 1

    - name: Build Solution
      run: dotnet build ./LeafLight-API.sln --no-restore --configuration Debug

    - name: Run Unit Tests
      run: dotnet test ./Unittest/Unittest.csproj --no-build --configuration Debug --verbosity normal

    - name: Build for Deployment
      if: ${{ success() }}
      run: dotnet build ./LeafLight-API.sln --configuration Release --no-restore

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t leaflight-api:v1 -f ./Dockerfile .

    - name: Push Docker Image to DockerHub
      run: |
        docker tag leaflight-api:v1 ${{ secrets.DOCKER_USERNAME }}/leaflight-api:v1
        docker push ${{ secrets.DOCKER_USERNAME }}/leaflight-api:v1

    - name: Deploy Container
      run: |
        docker container stop leaflight-api || true
        docker container rm leaflight-api || true
        docker run -d --name leaflight-api -p 5254:5254 ${{ secrets.DOCKER_USERNAME }}/leaflight-api:v1
