name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Lint Check
      run: |
        dotnet format style ./<SLN_NAME>.sln --verify-no-changes
        dotnet format analyzers ./<SLN_NAME>.sln --verify-no-changes
      env:
        DOTNET_NOLOGO: 1

    - name: Test
      id: unittests
      run: dotnet test --no-build --verbosity normal

    - name: Build
      if: ${{ steps.unittests.outcome == 'success' }}
      run: dotnet build --no-restore
