name: .NET CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore ./LeafLight-API.sln

    - name: Lint Check
      run: |
        dotnet format style ./LeafLight-API.sln --verify-no-changes
        dotnet format analyzers ./LeafLight-API.sln --verify-no-changes
      env:
        DOTNET_NOLOGO: 1

    - name: Build Solution
      run: dotnet build ./LeafLight-API.sln --no-restore --configuration Debug

    - name: Run Unit Tests
      run: dotnet test ./Unittest/Unittest.csproj --no-build --configuration Debug --verbosity normal

    - name: Build for Deployment
      if: ${{ success() }}
      run: dotnet build ./LeafLight-API.sln --configuration Release --no-restore
